run:
  skip-dirs:
    - docker
    - docs
    - scripts
    - templates
    - testdata
    - tests
    - tools
    - vendor
  tests: false
  issues-exit-code: 0

linters:
  presets:
    - bugs
    - unused
    - style
    - format
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - wsl
    - whitespace
    - godox
    - gomnd
  fast: false

linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 185
    # tab width in spaces. Default to 1.
    tab-width: 4
  gofmt:
    simplify: true
  funlen:
    lines: 200
    statements: 120

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
